### ISSUE TITLE
Font missing on Windows

### ISSUE THREAD

**Issue by kuboschek** [jacobs-hack/static-page#2]
`index.html` uses the Menlo font family, which isn't available on my PC.

OS: Windows 10
Browser: Firefox 60

**Comment by adamtouzani** [comment]
The font is included with the page – this is an issue only with Firefox that I have to look into... Thanks for noticing this!

**Comment by adamtouzani** [comment]
Issue fixed by @ngetahun

**Comment by adamtouzani** [comment]
Issue still prevalent on Windows (Chrome/Edge).
