### ISSUE TITLE
Write text for sections

### ISSUE THREAD

**Issue by kuboschek** [jacobs-hack/static-page#2]
This is more or less a job for marketing:

We need texts for:
- What is jacobsHack!
- Last year
- FAQ
- ... probably more

**Comment by alexachivu** [comment]
Hey guys! I was thinking that for the description we can use something like this: 

One of the biggest hackathons in Europe is back! For two years, JacobsHack has gathered together hundreds of passionate and creative people from all around the world. There are no conditions, just have fun, program and innovate your ideas during our 24-hours marathon! Our team will make sure you have a good time and a nice experience!

How does it sound?

**Comment by alexachivu** [comment]
Also, for the FAQ section, I came up with these questions:

•	Where is JacobsHack? 
•	How do I find Jacobs University?
•	Who can participate?
•	Do I get my money back for transportation?
•	Do I need a team?
•	What kind of food will I get? And how about special food requirements?

What else do you think we can include here?

**Comment by thunderboltsid** [comment]
@alexachivu Consider changing 4th one to "Are there travel reimbursements?" 
@kuboschek One thing I despise about the HackMIT template is that the FAQ is too cluttered. We might want to redesign that.

**Comment by kuboschek** [comment]
Maybe a live-search bar that narrows questions down, at least on desktop. Mobile is fine IMO since it's single column anyways.

**Comment by thunderboltsid** [comment]
@alexachivu take a look at the current website https://2016f.jacobshack.com/ and feel free to modify the wording
