### ISSUE TITLE
Color scheme!

### ISSUE THREAD

**Issue by kuboschek** [jacobs-hack/static-page#3]
Let's devise a color scheme / CD for our static page. Will go into stylesheets/scss/_constants.scss once ready.

Must include blue! :P

Ping @dkundel

**Comment by thunderboltsid** [comment]
@kuboschek The scheme is already defined by Jacobs colours if you look at old sites. It's Jacobs Blue #07457B, Jacobs Grey #E6E6E6, and White #FFFFFF.

**Comment by kuboschek** [comment]
But is that all? I feel like we could benefit from a refresh here

**Comment by dkundel** [comment]
Sorry only read this now. I'll devise a color scheme throughout the day tomorrow and send it to you.
